### PR TITLE
update readme

### PR DESCRIPTION
**Pull request by Ayushparikh-code**
resolved issue #1

### CODE REVIEW

**Comment by himanshu007-creator** [comment]
Thanks for your contribution @Ayushparikh-code

**Comment by Ayushparikh-code** [comment]
> Thanks for your contribution @Ayushparikh-code

So u guys gonna announce winner of that open-source day or that's just for experience ?

**Comment by himanshu007-creator** [comment]
> > Thanks for your contribution @Ayushparikh-code
> 
> So u guys gonna announce winner of that open-source day or that's just for experience ?

The process is underway.

**Comment by Ayushparikh-code** [comment]
> > > Thanks for your contribution @Ayushparikh-code
> > 
> > 
> > So u guys gonna announce winner of that open-source day or that's just for experience ?
> 
> The process is underway.

Underway means ?

**Comment by himanshu007-creator** [comment]
> > > > Thanks for your contribution @Ayushparikh-code
> > > 
> > > 
> > > So u guys gonna announce winner of that open-source day or that's just for experience ?
> > 
> > 
> > The process is underway.
> 
> Underway means ?

<a href="https://www.google.com/search?q=underway+meaning&oq=underway+m&aqs=chrome.0.0i433j0j69i57j0l7.4126j1j7&sourceid=chrome&ie=UTF-8">It</a> meant, results will be out soon.

**Pull request merged**
